#!/usr/bin/env python

Import('env')
Import('env_modules')

env_newton = env_modules.Clone()

# Thirdparty source files
if env['builtin_newton']:
    # Thirdparty source files

    # add the defines to link to proper libraries
    env_newton.Append(CPPDEFINES=['_NEWTON_STATIC_LIB'])
    env_newton.Append(CPPDEFINES=['_CNEWTON_STATIC_LIB'])
    env_newton.Append(CPPDEFINES=['_DVEHICLE_STATIC_LIB'])
    env_newton.Append(CPPDEFINES=['_CUSTOM_JOINTS_STATIC_LIB'])

    #add include path
    env_newton.Prepend (CPPPATH=["#thirdparty/newton/win32sdk/include/newton/"])
    env_newton.Prepend (CPPPATH=["#thirdparty/newton/win32sdk/include/dgCore/"])
    env_newton.Prepend (CPPPATH=["#thirdparty/newton/win32sdk/include/dMath/"])

    #add static libraries path to main enviroment for linking
    if (env["bits"] == "64"):
        env.Append(LIBPATH=['#thirdparty/newton/win64sdk/lib/'])
    else: 
        env.Append(LIBPATH=['#thirdparty/newton/win32sdk/lib/'])

    #add static libraries 
    env.Append(LINKFLAGS=['newton.lib'])
    env.Append(LINKFLAGS=['dgCore.lib'])
    env.Append(LINKFLAGS=['dgPhysics.lib'])
    


# Godot source files
env_newton.add_source_files(env.modules_sources, "*.cpp")
